/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'P-background-base': '#121212',
        'P-background-tinted-base': 'hsla(0,0%,100%,.07)',
        'P-text-base': '#fff',
        'P-text-subdued': '#a7a7a7',
        'P-text-bright-accent': '#1ed760',
        'P-text-positive': '#1ed760',
        'P-text-announcement': '#3d91f4',

        // 'P-background-base': '#121212',
        // 'P-background-highlight': '#1a1a1a',
        // 'P-background-press': '#000',
        // 'P-background-elevated-base': '#242424',
        // 'P-background-elevated-highlight': '#2a2a2a',
        // 'P-background-elevated-press': '#000',
        // 'P-background-tinted-base': 'hsla(0,0%,100%,.07)',
        // 'P-background-tinted-highlight': 'hsla(0,0%,100%,.1)',
        // 'P-background-tinted-press': 'hsla(0,0%,100%,.04)',
        // 'P-background-unsafe-for-small-text-base': '#121212',
        // 'P-background-unsafe-for-small-text-highlight': '#121212',
        // 'P-background-unsafe-for-small-text-press': '#121212',
        // 'P-text-base': '#fff',
        // 'P-text-subdued': '#a7a7a7',
        // 'P-text-bright-accent': '#1ed760',
        // 'P-text-negative': '#f15e6c',
        // 'P-essential-bright-accent': '#1ed760',
        // 'P-text-warning': '#ffa42b',
        // 'P-text-positive': '#1ed760',
        // 'P-text-announcement': '#3d91f4',
        // 'P-essential-base': '#fff',
        // 'P-essential-subdued': '#727272',
        // 'P-essential-negative': '#e91429',
        // 'P-essential-warning': '#ffa42b',
        // 'P-essential-positive': '#1ed760',
        // 'P-essential-announcement': '#0d72ea',
        // 'P-decorative-base': '#fff',
        // 'P-decorative-subdued': '#292929',
      },
    },
  },
  plugins: [],
};
